replicaCount: 1

image:
  repository: ghcr.io/kayaman/parrot
  pullPolicy: Always
  tag: 'latest'

nameOverride: ''
fullnameOverride: ''

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
