name: Deploy GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'helm/**'
      - '.github/workflows/pages.yaml'

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Create Helm Repository Structure
        run: |
          mkdir -p .gh-pages
          touch .gh-pages/.nojekyll
          echo "# Parrot Helm Repository" > .gh-pages/README.md
          echo "This is the Helm repository for the Parrot microservice." >> .gh-pages/README.md

      - name: Package Helm Chart
        run: |
          helm package helm/ -d .gh-pages/

      - name: Generate Helm Repository Index
        run: |
          helm repo index .gh-pages/ --url https://kayaman.github.io/parrot/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .gh-pages
          branch: gh-pages
          clean: true
