name: Deploy Helm Chart to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'helm/**'
      - '.github/workflows/pages.yaml'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  deploy-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Create Helm chart package directory
        run: |
          mkdir -p .deploy/charts
          mkdir -p .deploy/repo

      - name: Package Helm chart
        run: |
          helm package ./helm -d .deploy/charts/

      - name: Create or update index.yaml
        run: |
          if [ -f "index.yaml" ]; then
            cp index.yaml .deploy/repo/
            helm repo index .deploy/charts --url https://kayaman.github.io/parrot --merge .deploy/repo/index.yaml
          else
            helm repo index .deploy/charts --url https://kayaman.github.io/parrot
          fi
          cp .deploy/charts/index.yaml .deploy/repo/

      - name: Create GitHub Pages structure
        run: |
          # Create basic structure
          mkdir -p .deploy/site
          cp .deploy/repo/index.yaml .deploy/site/
          cp -r .deploy/charts/*.tgz .deploy/site/

          # Add .nojekyll file to disable Jekyll processing
          touch .deploy/site/.nojekyll

          echo "# Parrot Service Helm Repository" > .gh-pages/README.md
          echo "This is the Helm repository for the Parrot microservice." >> .gh-pages/README.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CR_PAT }}
          publish_dir: .deploy/site
          keep_files: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Helm chart to GitHub Pages'
