name: Deploy Helm Chart to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'helm/**'
      - '.github/workflows/pages.yaml'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  deploy-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Create Helm chart package directory
        run: |
          mkdir -p .deploy/charts
          mkdir -p .deploy/repo

      - name: Package Helm chart
        run: |
          helm package ./helm -d .deploy/charts/

      - name: Create or update index.yaml
        run: |
          if [ -f "index.yaml" ]; then
            cp index.yaml .deploy/repo/
            helm repo index .deploy/charts --url https://kayaman.github.io/parrot --merge .deploy/repo/index.yaml
          else
            helm repo index .deploy/charts --url https://kayaman.github.io/parrot
          fi
          cp .deploy/charts/index.yaml .deploy/repo/

      - name: Create GitHub Pages structure
        run: |
          # Create basic structure
          mkdir -p .deploy/site
          cp .deploy/repo/index.yaml .deploy/site/
          cp -r .deploy/charts/*.tgz .deploy/site/

          # Add .nojekyll file to disable Jekyll processing
          touch .deploy/site/.nojekyll

          # Install markdown to HTML converter
          npm install -g marked

          # Convert README.md to HTML for index.html
          cat > .deploy/convert_readme.js << EOF
          const fs = require('fs');
          const marked = require('marked');

          // Read README.md content
          const readme = fs.readFileSync('README.md', 'utf8');

          // Convert markdown to HTML
          const htmlContent = marked.parse(readme);

          // Create HTML wrapper
          const html = \`<!DOCTYPE html>
          <html>
            <head>
              <title>Parrot Helm Repository</title>
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <style>
                body { 
                  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                  max-width: 1000px; 
                  margin: 0 auto; 
                  padding: 20px;
                  line-height: 1.5;
                  color: #24292e;
                }
                h1, h2, h3 { margin-top: 24px; margin-bottom: 16px; font-weight: 600; line-height: 1.25; }
                h1 { font-size: 2em; padding-bottom: 0.3em; border-bottom: 1px solid #eaecef; }
                h2 { font-size: 1.5em; padding-bottom: 0.3em; border-bottom: 1px solid #eaecef; }
                code, pre { font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace; }
                pre { background-color: #f6f8fa; padding: 16px; overflow: auto; border-radius: 3px; }
                code { padding: 0.2em 0.4em; background-color: rgba(27,31,35,0.05); border-radius: 3px; }
                pre code { background-color: transparent; padding: 0; }
                blockquote { padding: 0 1em; color: #6a737d; border-left: 0.25em solid #dfe2e5; margin: 0; }
                a { color: #0366d6; text-decoration: none; }
                a:hover { text-decoration: underline; }
                hr { height: 0.25em; padding: 0; margin: 24px 0; background-color: #e1e4e8; border: 0; }
                table { border-spacing: 0; border-collapse: collapse; }
                table th, table td { padding: 6px 13px; border: 1px solid #dfe2e5; }
                table tr { background-color: #fff; }
                table tr:nth-child(2n) { background-color: #f6f8fa; }
              </style>
            </head>
            <body>
              <div class="markdown-body">
                \${htmlContent}
                <hr>
                <p><em>This page is generated from the project README.md. This is also a Helm chart repository.</em></p>
                <p><code>helm repo add parrot https://kayaman.github.io/parrot</code></p>
              </div>
            </body>
          </html>\`;

          // Write HTML file
          fs.writeFileSync('.deploy/site/index.html', html);
          EOF

          # Execute the conversion script
          node .deploy/convert_readme.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CR_PAT }}
          publish_dir: .deploy/site
          keep_files: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Helm chart to GitHub Pages'
